# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: store data
          command: echo "Hello World" > /output/hello_world.txt
      - persist_to_workspace:
          root: /output
          paths:
            - hello_world.txt
  print_output_file:
    docker:
      - image: alpine:latest
    steps:
      - run: cat /output/hello_world.txt

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
